### ISSUE TITLE
Using Rank2Types to safely extract a non-random value.

### ISSUE THREAD

**Issue by agrif** [byorgey/MonadRandom#12]
Have you ever considered adding the following function to your library?

~~~~{.hs}
constRand :: (forall g. Rand g a) -> a
constRand r = evalRand r (mkStdGen 0)
~~~~

This would be useful for code that incorporates Rand (or RandT) but has parts that do not always produce a random value. Here the Rank 2 `forall` guarantees that whatever `Rand g a` is passed in can't actually depend on `g`, and therefore has only one value.

I'd be happy to write up a PR for this, but since it needs Rank2Types I thought I'd ask first.

**Comment by agrif** [comment]
A friend on IRC pointed out that while the rank 2 type above is needed if it's implemented outside the package (since it doesn't expose constructors), inside the package it's much simpler:

~~~~{.hs}
constRand :: Rand () a -> a
constRand (Rand x) = evalStateT x ()
~~~~

Of course, this is just `evalRandT r ()`, except without the `RandomGen ()` restriction. Is there a reason to keep that restriction in place?

**Comment by byorgey** [comment]
This all seems to make sense but to be honest I'm not sure I see the value of it.  Can you give a more specific example of where you would want to use it?

**Comment by agrif** [comment]
Right now I'm writing a toy raytracer built around a type that looks like

~~~~{.hs}
type Caster g a = Ray -> Maybe (Rand g a)
~~~~

It makes sense to build `Rand` into the type itself, since 99% of the time the result is going to have some element of randomness (random bounces off a surface, etc.). However, there's a small amount of parts that work the same way but have no random element, for example testing if a ray intersects a sphere. The type checker already infers enough info to know that sphere intersection isn't truly random, I just want a way to use that.

**Comment by byorgey** [comment]
Ah, this makes sense, thanks.  And I see what you mean about the `RandomGen` constraints.  Actually now that I look at it, there are quite a lot of functions with what seems like an unnecessary `RandomGen` constraint.  I cannot think of any reason why it is needed.  I would be happy to merge a pull request adding `constRand` or just removing the unnecessary `RandomGen` constraints.
