### ISSUE TITLE
Min constraint on mtl

### ISSUE THREAD

**Issue by crockeea** [byorgey/MonadRandom#14]
MonadRandom-0.2 (and possibly later) requires Control.Monad.Exception from mtl, which isn't introduced until mtl-2.2.1.

**Comment by byorgey** [comment]
Thanks for the report!  I'll look into this more carefully soon.

**Comment by byorgey** [comment]
I have revised all versions of `MonadRandom` back to 0.2 to reflect the `mtl` constraint.
