### ISSUE TITLE
Min constraint on mtl breaks LTS Haskell and causes cabal hell

### ISSUE THREAD

**Issue by mwu-tow** [byorgey/MonadRandom#15]
The change resulting from #14 broke my builds.
I use stack and `lts-2.22` resolver (latest available for GHC 7.8.4). The lts-2.22 contains:
MonadRandom 0.3.0.2
mtl  2.1.3.1

Overriding `mtl` requires bumping `transformers` as well (GHC 7.8.4 ships 0.3.0.0) and that breaks compilation of `ghc-mtl-1.2.1.0` and causes warnings about packages depending on multiple version of the same package and that things will likely explode. Well, I haven't been able to fix this on my side.

Please consider reverting the `mtl` constraint at least on `MonadRandom 0.3.0.2` to fix the LTS.

**Comment by byorgey** [comment]
Yikes, I'm so sorry.  I was convinced that `MonadRandom` would not actually build with `mtl-2.1`.  When I relax the lower bound on `mtl` and try to build with `mtl-2.1`, this is what I get:

```
$ cabal install --dry-run --constraint='mtl < 2.2'
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: MonadRandom-0.4 (user goal)
next goal: mtl (dependency of MonadRandom-0.4)
rejecting: mtl-2.2.1, 2.2.0.1, 2.2 (global constraint requires <2.2)
trying: mtl-2.1.3.1
trying: transformers-compat-0.4.0.4 (dependency of MonadRandom-0.4)
next goal: transformers (dependency of MonadRandom-0.4)
rejecting: transformers-0.4.2.0/installed-c1a..., 0.4.3.0, 0.4.2.0, 0.4.1.0
(conflict: mtl => transformers==0.3.*)
rejecting: transformers-0.3.0.0 (conflict: transformers-compat-0.4.0.4:three
=> transformers>=0.4.1 && <0.5)
rejecting: transformers-0.2.2.1, 0.2.2.0, 0.2.1.0, 0.2.0.0, 0.1.4.0, 0.1.3.0,
0.1.1.0, 0.1.0.1, 0.1.0.0, 0.0.1.0, 0.0.0.0 (conflict: MonadRandom =>
transformers>=0.3 && <0.5)
rejecting: transformers-0.4.0.0 (conflict: mtl => transformers==0.3.*)
Dependency tree exhaustively searched.
```

Now I am really confused.

**Comment by byorgey** [comment]
Hmm, but you're right that it does work with `mtl-2.1` when building with `stack` on `lts-2.22`.  I will revise the lower bound to include `mtl-2.1`.

**Comment by byorgey** [comment]
New revisions with `mtl-2.1` as a lower bound are now published.  Let me know if this fixes things for you.

**Comment by mwu-tow** [comment]
Yes, it fixes my issues. Thank you for the prompt reaction.

**Comment by byorgey** [comment]
Great, no problem.
