### ISSUE TITLE
Unnecessary `Monad` constraint on `liftRandT`

### ISSUE THREAD

**Issue by echatav** [byorgey/MonadRandom#16]
The constraint in the type signature `liftRandT :: Monad m => (g -> m (a, g)) -> RandT g m a` is unnecessary. Normally I wouldn't mind but it's makes it impossible to make an `MFunctor` instance from the `mmorph` library, because for some reason the type signature `hoist :: MFunctor t => Monad m => (forall a. m a -> n a) -> t m b -> t n b` doesn't constrain `n` to be a `Monad`. Is there a trick to get around this?

**Comment by byorgey** [comment]
Hmm, you're right.  There no trick to get around this that I know of, but I'm happy to put out a new release relaxing the constraint.  I'll get around to it eventually, or if you wanted to submit a pull request it would probably happen faster.

**Comment by echatav** [comment]
PR #17
