### ISSUE TITLE
Control.Monad.Random has no Safe Haskell tag

### ISSUE THREAD

**Issue by Lokathor** [byorgey/MonadRandom#22]
Control.Monad.Random.Class is marked as Safe, but Control.Monad.Random isn't marked at all. It should probably be marked as Trustworthy (System.Random is only Trustworthy, so Control.Monad.Random can't be Safe).

If it can't at least be marked as Trustworthy because of some weird operation then that's a big concern after all.

**Comment by byorgey** [comment]
Thanks for bringing this up.  Control.Monad.Random also can't be marked Safe because it uses `GeneralizedNewtypeDeriving`, but I agree it should be Trustworthy.

**Comment by byorgey** [comment]
Released as `MonadRandom-0.4.2.3`.
