### ISSUE TITLE
Move MonadRandom instances so they are no longer orphans

### ISSUE THREAD

**Issue by andrewthad** [byorgey/MonadRandom#23]
Since `MonadRandom` is an mtl style typeclass and this library depends on `transformers`, it seems like it should provide the usual pass through instances. Things like:

```
instance MonadRandom m => MonadRandom (ReaderT r m) where ...
```

Is there a reason these were omitted, or would you take a PR for this?

**Comment by byorgey** [comment]
But the library does provide these instances.  For example, the one you mention is here:

https://github.com/byorgey/MonadRandom/blob/master/Control/Monad/Random.hs#L182

Did you encounter a situation where these did not work for you?

**Comment by andrewthad** [comment]
Ah, it looks like there are two problems. One is that I was trying to use the pass through instance for `ListT`, which doesn't exist. That's fine though because people shouldn't really use `ListT` anyway. The second problem is that these instances are all defined as orphans. I've actually run into this issue in both [text-show](https://github.com/RyanGlScott/text-show/issues/18) and in [aeson](https://github.com/bos/aeson/issues/375) recently. There might be a haddock fix for this at some point in the future. In this case, it seems like the instances could just be moved to the `Class` module so that they would not longer be orphans.

**Comment by byorgey** [comment]
Ah, yes, making them non-orphans so they show up in the Haddocks is a good idea.  Would you be willing to make a PR for that?

**Comment by andrewthad** [comment]
Yeah.

**Comment by byorgey** [comment]
Thanks!  I'll leave this issue open with a different title.

**Comment by andrewthad** [comment]
PR is up.
