### ISSUE TITLE
Why aren't Applicative/Alternative derived

### ISSUE THREAD

**Issue by Icelandjack** [byorgey/MonadRandom#32]
Quick question, is there a reason why `Applicative` and `Alternative` aren't included in the [`deriving` list](https://hackage.haskell.org/package/MonadRandom-0.4.2.3/docs/src/Control-Monad-Random.html)?

```haskell
newtype RandT g m a = RandT (StateT g m a)
    deriving (Functor, Monad, MonadPlus, MonadTrans, MonadIO, MonadFix, MonadReader r, MonadWriter w)
```

**Comment by byorgey** [comment]
Thanks for the question; there was no particular reason, the code probably dated from before those classes existed and no one had thought to add them.  This is now fixed in HEAD by https://github.com/byorgey/MonadRandom/commit/b7c37aa1b549479a6e5343c74672dd754170de19 .
