### ISSUE TITLE
Pick a license other than "OtherLicense"

### ISSUE THREAD

**Issue by ndmitchell** [byorgey/MonadRandom#35]
If you want to automatically find which subset of licenses a project is using the OtherLicense in MonadRandom is pretty annoying. Phrases like "in theory" should not appear in any license documents - are you granting me rights to use the code, or granting me license to a lawsuit? I suggest you just license it to BSD like everything else on Hackage - the BSD3 seems strictly less permissive than the above license so you wouldn't need to check with anyone.

I'm rather surprised the Debian people haven't been all over this already - they are usually pretty hot on any non-standard licenses.

**Comment by byorgey** [comment]
Thanks for filing the ticket!  To be honest I inherited the package from someone else and never really paid much attention to the license.  The suggestion that using a BSD3 license means I wouldn't have to check with anyone seems good, I'll look into it.

**Comment by ndmitchell** [comment]
As with all license advice, I should mention I'm not a lawyer (although you knew that!) so getting a second opinion might be useful or reading the texts yourself.

**Comment by byorgey** [comment]
Done.  After thinking about it a bit, I am quite sure this is fine.  Specifically, under the terms of the old license I am free to release this modified version of the original work under a different license.

**Comment by ndmitchell** [comment]
Thanks!

**Comment by byorgey** [comment]
Sure.  Good timing too --- an 0.5 release is imminent!
