### ISSUE TITLE
fromList for non-empty lists

### ISSUE THREAD

**Issue by Icelandjack** [byorgey/MonadRandom#37]
I noticed that 'fromList' fails on the empty list, now that `Data.List.NonEmpty` is in base that is an option

**Comment by byorgey** [comment]
HEAD now has `fromListMay` as well (which returns a `Maybe`).  I'm not terribly inclined to also add a `NonEmpty` variant at this point, especially since that would only work on recent versions of base and I want `MonadRandom` to continue to work on older versions as well.
