### ISSUE TITLE
`Foldable` constraint on fromList, uniform

### ISSUE THREAD

**Issue by Icelandjack** [byorgey/MonadRandom#38]
`uniform` would arguably be more useful but I leave that question up to you 

```haskell
uniform :: (MonadRandom m, Foldable f) => f a -> m a
```

**Comment by byorgey** [comment]
Versions generalized to `Foldable` are already included in HEAD and will be included in an upcoming 0.5 release.

**Comment by Icelandjack** [comment]
Thank you for a speedy response
