### ISSUE TITLE
Add 'shuffle'?

### ISSUE THREAD

**Issue by Icelandjack** [byorgey/MonadRandom#39]
I know it exists in other packages, but should this library provide a `shuffle` function alongside weighted/uniform?

It *could* even be given a `Traversable` constraint

**Comment by byorgey** [comment]
Well, the `random-shuffle` package (http://hackage.haskell.org/package/random-shuffle) already provides `shuffleM :: MonadRandom m => [a] -> m [a]` which depends on this package.   I see no good reason to move it here, unless we wanted to generalize it to work over any `Traversable` as you suggest, though off the top of my head I am not sure how that would work.
