### ISSUE TITLE
Replacing head in fromListMay

### ISSUE THREAD

**Issue by gilgamec** [byorgey/MonadRandom#44]
I ran into this one while picking from a distribution using `weighted`. Occasionally, my program would crash with
```
*** Exception: Prelude.head: empty list
```
which was confusing, since I never used `head` in my code. Eventually, I tracked it down to `MonadRandom`. It turned out that my weights would occasionally go negative, and then it was possible for the `head` in `fromListMay` to fail.

Turns out this is simple to fix; just replace
```
Just . fst . head
```
with
```
fmap fst . listToMaybe
```
and then instead of the generic `head` exception, we get the error
```
*** Exception: Control.Monad.Random.Class.weighted: empty collection, or total weight = 0
```
which may not be precisely correct, but at least gives up where the problem is.

**Comment by byorgey** [comment]
Thanks for the report!
