### ISSUE TITLE
Drop support of GHC 7.4?

### ISSUE THREAD

**Issue by Bodigrim** [byorgey/MonadRandom#48]
https://matrix.hackage.haskell.org/#/package/MonadRandom/

Several latest releases fail to build with prehistoric GHCs. The reasons are:
1. Before GHC 7.6 hiding non-existent entries was an error instead of warning. Old versions of `random` do not have `uniform{,R}`:
https://github.com/byorgey/MonadRandom/blob/748610a247812ddd97c4833f9922f6be5ada9eb8/Control/Monad/Random/Strict.hs#L45
2. GHC 7.0 does not support Safe Haskell:
https://github.com/byorgey/MonadRandom/blob/5d7d8048a49afed15b9c9877f5c57984adfc3192/Control/Monad/Random.hs#L1

This can be worked around with CPP, but I guess it's acceptable these days just require `base >= 4.6`. 

I'd appreciate revisions for existing releases.

**Comment by Bodigrim** [comment]
As a Hackage Trustee, I've made necessary revisions:
https://hackage.haskell.org/package/MonadRandom-0.5.3/revisions/
https://hackage.haskell.org/package/MonadRandom-0.5.2/revisions/
https://hackage.haskell.org/package/MonadRandom-0.5.1.2/revisions/

**Comment by byorgey** [comment]
Thank you!  I will soon update the repo to match.
