### ISSUE TITLE
Support transformers-0.6 and mtl-2.3

### ISSUE THREAD

**Issue by andreasabel** [byorgey/MonadRandom#50]
As `mtl-2.3` is out now, `transformers-0.6` is available. 
Supporting it will require some code changes (`ErrorT` -> `ExceptT`, removal of `ListT`).

**Comment by byorgey** [comment]
Thanks for the nudge! I saw the mtl release announcement and definitely plan to spend some time in the next few days updating packages.

**Comment by andreasabel** [comment]
There will be some revision of `mtl-2.3` concerning the missing export of `ExceptT`:
- https://github.com/haskell/mtl/issues/117

**Comment by byorgey** [comment]
Ah, good to know.  I will wait until the revised version drops.

**Comment by phadej** [comment]
@byorgey the `mtl` maintainers indicated that it might take some time.

If you anyway decide to wait, make sure to disallow `mtl-2.3` point release, if it needs `ExceptT` re-export.

**Comment by phadej** [comment]
I made revision to `MonadRandom-0.1.9..0.1.13`, as these had invalid `mtl` bounds (both upper and lower).

**Comment by byorgey** [comment]
Uploaded `MonadRandom-0.6` to Hackage, which supports `transformers-0.6` and `mtl-2.3.1`.  The major version bump is necessary since I removed instances for the deprecated `ErrorT` and `ListT` transformers.
