### ISSUE TITLE
MonadRandom should have a lower bound on mtl / CPP code for mtl versions

### ISSUE THREAD

**Issue by co-dan** [byorgey/MonadRandom#9]
I tried to install MonadRandom and bumped into the issue when MonadRandom was importing a module `Control.Monad.Except`, which is only available in the latest mtl (v 2.2.1)

Now, the [code that imports that module](https://github.com/byorgey/MonadRandom/blob/master/Control/Monad/Random.hs#L53) checks for the version of transformers, but not for the version of mtl.
(transformers export `Control.Monad.Trans.Except`, not `Control.Monad.Except`)

**Comment by byorgey** [comment]
Ah, thanks for the report!  Should have tested that more thoroughly.

**Comment by byorgey** [comment]
I believe this has been addressed by https://github.com/byorgey/MonadRandom/commit/6a2f883abd9b4abc5687e74c166cfb5e652597e1.  Let me know if it is otherwise.
